service: user-service

frameworkVersion: '3'

plugins:
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs20.x
  stage: ${env:STAGE, 'dev'}
  region: ${env:REGION, 'us-east-1'}
  # This 'ecr' section tells Serverless to manage container images.
  ecr:
    images:
      # Define a logical name for our image.
      user-service-image:
        # Path to the Docker build context (the root of our repo).
        path:../../../
        # The 'file' property is removed as Serverless will automatically find 'Dockerfile'.
        # Pass the service name as a build argument to our Dockerfile.
        buildArgs:
          service: user-service

functions:
  createUser:
    # Instead of a 'handler' property, we now use the 'image' property
    # to point to the logical image name defined above.
    image:
      name: user-service-image
    events:
      - httpApi:
          path: /users
          method: post